version: "3.5"
services:
  nodejs:
    build: .
    container_name: "philips-dynalite-mqtt"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
      - /usr/src/app/config
    networks:
      - app
  bash:
    build: .
    entrypoint: /bin/sh
networks:
  app:
