version: "3.5"
services:
  nodejs:
    build: .
    container_name: "philips-dynalite-mqtt"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    networks:
      - app
networks:
  app:
